[package]
name = "libairs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vers-vecs = { git = "https://github.com/Cydhra/vers", rev = "756c503" }
bio-seq = "0.10"