[package]
name = "libairs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.8.0"
radix-heap = "0.3.7" # 0.3.7 was the last one that supported peek_key
twox-hash = "1.6"

[profile.release]
debug = true
