[package]
name = "libairs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio-seq = "0.10"
rayon = "1.8.0"
puffin = "0.18.1"
puffin_http = "0.15.0"

[profile.release]
debug = true
